[firebase]

# 🔐 Service Account (from JSON file)
type = "service_account"
project_id = "faircredit-b3d73"
private_key_id = "e9a319c49523a6b8c196f439a83f3569ce647cae"

private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDdwETF6oz2Oo41
gDS+W2cOT0Jx+hgcpAkZVPmkTWwFL+mnimAx5MAZ0teMvrTObL8xjuDUDxWIdf/t
Dy3MsNWBdzZRk2fjZvxsCpFFeNTG6yFq96H/0ZicgPTQVt0Y7KrxISVtyhr4vqwy
TMFRhnthGXzShqf3941zTObv7muY34QwBXdUbe2uU4x+xNbMy9iS00JzqW8jeldY
q9Ax/xt4OWx9Dt4b/Yy0SizNWn4xwyinTfoSVhwAZrlXyWEuUoGvAwhylwk/8SwM
npsEHG++mq6II03hnqX4qu8A5DuXQIlDsm4xpEcRmG8MRSY4cXXllj2leSq0EKBH
Kw53k4eNAgMBAAECggEAGylvYxzBSnHOtH/xNfXlMCwGNAbRyERRdwBhGb6AAjyl
rqd08/eUjjU0wOElLXnFi5D4OhFk7lOh1ww6bG2moVaUWTaojYKyXZuHws4zpe/s
JnmRps+qFVV4Z0KUj3aB08pfFs0gM6LLXdfoAA/sce7YysLCtU1lzp83VGFMXauc
uU2zUu1XFD7XNqb98Y0/i9GsEGsht+Gz7JIWHQXmDAUpaZueNoOPVleyFeMV3SaI
Zs4c4pguRvUmRKv6gvMtltk9SHt7KeTGO9VODRCnACol4kMihIadquNxctZOiuNi
9VmFzFvvmGzUztmqySWL4m2Ok/3Cv9Ev856mdWh58QKBgQD+7EEelIgHC+sXvDVu
R+fnuoLUzGnjumKKr43OLrNYL12ohau+zXZ4Ha5/7ZQ2p+nlJzitwX0EvvruHhzh
UD07oq8N7dVdvPOOUsVSEJZEpF87OHECUpeQrq082fum16HVJpHsrZZhJ4QLSsTR
K6JEPEpjCnCwLPCab+7hVBhmZQKBgQDesCIFRcCvRR2D2CjMRVOmUKVCrZqmqRFM
zanLIESZ6NBd6JbObbUuxf8EH6Eqv/hOqsiw/LQBpTluhpHRPPNvyrP/Dk6nFTna
XLIcgA752obGIiwfl7q/VBCYnWOaHaamL6PTZe0l7DwNyiDhRyh8bdrBJ9F98AfP
N/y6WOpWCQKBgQDl811GZXtSx+h4D5ku8oP5Xx/XLtEx0BZFvdgvraavnIJimrly
ssnzzepzkW6J4uu0fq285vWMC240z0sD36psmfJIoUo/dUtKDdXakgXKw27375DZ
JIF9zGOOqZ88P/TGXjVxhqBI4SlWOkrR2AdWgAAl2OwPr2oWFXQpI/+ilQKBgAl0
000EBEWtGq7BnCHog7/ZRttJAfs3zLtFNIOisCcVAtwqB1VmxT3iPI0RRsfI9SNq
DzGs2XwEZybxYfnPq8rAgdo/4kkoFpfWPd4F9hzYEccSJmuFBvIfAMFqVZNy1OPT
vBI7DtIAcSBox/KpEegOxi5ToYrGiZ5cE0hahED5AoGAFW+0vnmK3ZG5HPpEnzWH
c8jR4KBMIOj0kS0hOTGICNwkUvDXjqGcYCPSxgxNM+vG6igCRCuDkUcXMESZwrYk
x/Ao74KRg5xb1uUWKsu6FXWYT3cqV5x/4TgguCRREyt832GaxUhbLCJYd5SykyiM
TYl4KW3pL6EaWeJlQAg1i+w=
-----END PRIVATE KEY-----"""

client_email = "firebase-adminsdk-fbsvc@faircredit-b3d73.iam.gserviceaccount.com"
client_id = "112825267799022480387"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40faircredit-b3d73.iam.gserviceaccount.com"



# 🌐 Web API Key (from Firebase → General → Your apps)
web_api_key = "AIzaSyA5weP7t0Z6YdN_VawzX4oXUaODjCg2GqI"





